services:
- type: pserv
  name: demo-taskmngr-db
  plan: starter
  env: docker
  region: ohio
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 1
  envVars:
  - fromGroup: demo-taskmngr-db

envVarGroups:
- name: demo-taskmngr-db
  envVars:
  - key: MYSQL_DATABASE
    value: demo-taskmngr-db
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true